resource "aws_cloudwatch_dashboard" "waf-dashboard" {
  dashboard_name = "${var.prefix}-waf-dashboard"

  dashboard_body = jsonencode({
    widgets = [
      {
        type   = "metric"
        x      = 12
        y      = 24
        width  = 24
        height = 6

        properties = {
          view = "table"
          stacked = false
          metrics = [
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "WordPressExploitableCommands_QUERYSTRING",
              "LabelNamespace",
              "awswaf:managed:aws:wordpress-app"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "WordPressExploitableCommands_QUERYSTRING",
              "LabelNamespace",
              "awswaf:managed:aws:wordpress-app"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "WordPressExploitablePaths_URIPATH",
              "LabelNamespace",
              "awswaf:managed:aws:wordpress-app"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "WordPressExploitablePaths_URIPATH",
              "LabelNamespace",
              "awswaf:managed:aws:wordpress-app"
            ]
          ]
          period = 300
          stat   = "Average"
          region = "${var.aws_region}"
          title  = "AWSManagedRulesWordPressRuleSet"
        }
      },
      {
        type   = "metric"
        x      = 12
        y      = 24
        width  = 24
        height = 12

        properties = {
          view = "table"
          stacked = false
          metrics = [
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "PowerShellCommands_Cookie",
              "LabelNamespace",
              "awswaf:managed:aws:windows-os"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "PowerShellCommands_Cookie",
              "LabelNamespace",
              "awswaf:managed:aws:windows-os"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "PowerShellCommands_Body",
              "LabelNamespace",
              "awswaf:managed:aws:windows-os"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "PowerShellCommands_Body",
              "LabelNamespace",
              "awswaf:managed:aws:windows-os"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "WindowsShellCommands_Body",
              "LabelNamespace",
              "awswaf:managed:aws:windows-os"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "WindowsShellCommands_Body",
              "LabelNamespace",
              "awswaf:managed:aws:windows-os"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "PowerShellCommands_QueryArguments",
              "LabelNamespace",
              "awswaf:managed:aws:windows-os"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "PowerShellCommands_QueryArguments",
              "LabelNamespace",
              "awswaf:managed:aws:windows-os"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "WindowsShellCommands_QueryArguments",
              "LabelNamespace",
              "awswaf:managed:aws:windows-os"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "WindowsShellCommands_QueryArguments",
              "LabelNamespace",
              "awswaf:managed:aws:windows-os"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "WindowsShellCommands_Cookie",
              "LabelNamespace",
              "awswaf:managed:aws:windows-os"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "WindowsShellCommands_Cookie",
              "LabelNamespace",
              "awswaf:managed:aws:windows-os"
            ]
          ]
          period = 300
          stat   = "Average"
          region = "${var.aws_region}"
          title  = "AWSManagedRulesWindowsRuleSet"
        }
      },
      {
        type   = "metric"
        x      = 12
        y      = 24
        width  = 24
        height = 6

        properties = {
          view = "table"
          stacked = false
          metrics = [
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "UNIXShellCommandsVariables_QUERYARGUMENTS",
              "LabelNamespace",
              "awswaf:managed:aws:posix-os"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "UNIXShellCommandsVariables_QUERYARGUMENTS",
              "LabelNamespace",
              "awswaf:managed:aws:posix-os"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "UNIXShellCommandsVariables_BODY",
              "LabelNamespace",
              "awswaf:managed:aws:posix-os"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "UNIXShellCommandsVariables_BODY",
              "LabelNamespace",
              "awswaf:managed:aws:posix-os"
            ]
          ]
          period = 300
          stat   = "Average"
          region = "${var.aws_region}"
          title  = "AWSManagedRulesUnixRuleSet"
        }
      },
      {
        type   = "metric"
        x      = 12
        y      = 24
        width  = 24
        height = 8

        properties = {
          view = "table"
          stacked = false
          metrics = [
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "PHPHighRiskMethodsVariables_HEADER",
              "LabelNamespace",
              "awswaf:managed:aws:php-app"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "PHPHighRiskMethodsVariables_HEADER",
              "LabelNamespace",
              "awswaf:managed:aws:php-app"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "PHPHighRiskMethodsVariables_QUERYSTRING",
              "LabelNamespace",
              "awswaf:managed:aws:php-app"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "PHPHighRiskMethodsVariables_QUERYSTRING",
              "LabelNamespace",
              "awswaf:managed:aws:php-app"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "PHPHighRiskMethodsVariables_BODY",
              "LabelNamespace",
              "awswaf:managed:aws:php-app"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "PHPHighRiskMethodsVariables_BODY",
              "LabelNamespace",
              "awswaf:managed:aws:php-app"
            ]
          ]
          period = 300
          stat   = "Average"
          region = "${var.aws_region}"
          title  = "AWSManagedRulesPHPRuleSet"
        }
      },
      {
        type   = "metric"
        x      = 12
        y      = 24
        width  = 24
        height = 8

        properties = {
          view = "table"
          stacked = false
          metrics = [
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "LFI_URIPATH",
              "LabelNamespace",
              "awswaf:managed:aws:linux-os"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "LFI_URIPATH",
              "LabelNamespace",
              "awswaf:managed:aws:linux-os"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "LFI_QUERYSTRING",
              "LabelNamespace",
              "awswaf:managed:aws:linux-os"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "LFI_QUERYSTRING",
              "LabelNamespace",
              "awswaf:managed:aws:linux-os"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "LFI_HEADER",
              "LabelNamespace",
              "awswaf:managed:aws:linux-os"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "LFI_HEADER",
              "LabelNamespace",
              "awswaf:managed:aws:linux-os"
            ]
          ]
          period = 300
          stat   = "Average"
          region = "${var.aws_region}"
          title  = "AWSManagedRulesLinuxRuleSet"
        }
      },
      {
        type   = "metric"
        x      = 12
        y      = 24
        width  = 24
        height = 20

        properties = {
          view = "table"
          stacked = false
          metrics = [
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "JavaDeserializationRCE_BODY",
              "LabelNamespace",
              "awswaf:managed:aws:known-bad-inputs"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "JavaDeserializationRCE_BODY",
              "LabelNamespace",
              "awswaf:managed:aws:known-bad-inputs"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "JavaDeserializationRCE_URIPATH",
              "LabelNamespace",
              "awswaf:managed:aws:known-bad-inputs"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "JavaDeserializationRCE_URIPATH",
              "LabelNamespace",
              "awswaf:managed:aws:known-bad-inputs"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "JavaDeserializationRCE_QUERYSTRING",
              "LabelNamespace",
              "awswaf:managed:aws:known-bad-inputs"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "JavaDeserializationRCE_QUERYSTRING",
              "LabelNamespace",
              "awswaf:managed:aws:known-bad-inputs"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "JavaDeserializationRCE_HEADER",
              "LabelNamespace",
              "awswaf:managed:aws:known-bad-inputs"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "JavaDeserializationRCE_HEADER",
              "LabelNamespace",
              "awswaf:managed:aws:known-bad-inputs"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "Host_localhost_HEADER",
              "LabelNamespace",
              "awswaf:managed:aws:known-bad-inputs"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "Host_localhost_HEADER",
              "LabelNamespace",
              "awswaf:managed:aws:known-bad-inputs"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "PROPFIND_METHOD",
              "LabelNamespace",
              "awswaf:managed:aws:known-bad-inputs"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "PROPFIND_METHOD",
              "LabelNamespace",
              "awswaf:managed:aws:known-bad-inputs"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "ExploitablePaths_URIPATH",
              "LabelNamespace",
              "awswaf:managed:aws:known-bad-inputs"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "ExploitablePaths_URIPATH",
              "LabelNamespace",
              "awswaf:managed:aws:known-bad-inputs"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "Log4JRCE_QUERYSTRING",
              "LabelNamespace",
              "awswaf:managed:aws:known-bad-inputs"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "Log4JRCE_QUERYSTRING",
              "LabelNamespace",
              "awswaf:managed:aws:known-bad-inputs"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "Log4JRCE_BODY",
              "LabelNamespace",
              "awswaf:managed:aws:known-bad-inputs"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "Log4JRCE_BODY",
              "LabelNamespace",
              "awswaf:managed:aws:known-bad-inputs"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "Log4JRCE_URIPATH",
              "LabelNamespace",
              "awswaf:managed:aws:known-bad-inputs"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "Log4JRCE_URIPATH",
              "LabelNamespace",
              "awswaf:managed:aws:known-bad-inputs"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "Log4JRCE_HEADER",
              "LabelNamespace",
              "awswaf:managed:aws:known-bad-inputs"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "Log4JRCE_HEADER",
              "LabelNamespace",
              "awswaf:managed:aws:known-bad-inputs"
            ]
          ]
          period = 300
          stat   = "Average"
          region = "${var.aws_region}"
          title  = "AWSManagedRulesKnownBadInputsRuleSet"
        }
      },
      {
        type   = "metric"
        x      = 12
        y      = 24
        width  = 24
        height = 36

        properties = {
          view = "table"
          stacked = false
          metrics = [
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "NoUserAgent_Header",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "NoUserAgent_Header",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "UserAgent_BadBots_HEADER",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "UserAgent_BadBots_HEADER",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "SizeRestrictions_QUERYSTRING",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "SizeRestrictions_QUERYSTRING",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "SizeRestrictions_Cookie_HEADER",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "SizeRestrictions_Cookie_HEADER",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "SizeRestrictions_BODY",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "SizeRestrictions_BODY",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "SizeRestrictions_URIPATH",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "SizeRestrictions_URIPATH",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "EC2MetaDataSSRF_BODY",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "EC2MetaDataSSRF_BODY",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "EC2MetaDataSSRF_COOKIE",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "EC2MetaDataSSRF_COOKIE",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "EC2MetaDataSSRF_URIPATH",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "EC2MetaDataSSRF_URIPATH",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "EC2MetaDataSSRF_QUERYARGUMENTS",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "EC2MetaDataSSRF_QUERYARGUMENTS",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "GenericLFI_QUERYARGUMENTS",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "GenericLFI_QUERYARGUMENTS",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "GenericLFI_URIPATH",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "GenericLFI_URIPATH",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "GenericLFI_BODY",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "GenericLFI_BODY",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "RestrictedExtensions_URIPATH",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "RestrictedExtensions_URIPATH",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "RestrictedExtensions_QUERYARGUMENTS",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "RestrictedExtensions_QUERYARGUMENTS",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "GenericRFI_QUERYARGUMENTS",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "GenericRFI_QUERYARGUMENTS",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "GenericRFI_BODY",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "GenericRFI_BODY",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "GenericRFI_URIPATH",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "GenericRFI_URIPATH",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "CrossSiteScripting_COOKIE",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "CrossSiteScripting_COOKIE",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "CrossSiteScripting_QUERYARGUMENTS",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "CrossSiteScripting_QUERYARGUMENTS",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "CrossSiteScripting_BODY",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "CrossSiteScripting_BODY",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "CrossSiteScripting_URIPATH",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "CrossSiteScripting_URIPATH",
              "LabelNamespace",
              "awswaf:managed:aws:core-rule-set"
            ]
          ]
          period = 300
          stat   = "Average"
          region = "${var.aws_region}"
          title  = "AWSManagedRulesCommonRuleSet"
        }
      },
      {
        type   = "metric"
        x      = 12
        y      = 24
        width  = 24
        height = 6

        properties = {
          view = "table"
          stacked = false
          metrics = [
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "AnonymousIPList",
              "LabelNamespace",
              "awswaf:managed:aws:anonymous-ip-list"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "AnonymousIPList",
              "LabelNamespace",
              "awswaf:managed:aws:anonymous-ip-list"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "HostingProviderIPList",
              "LabelNamespace",
              "awswaf:managed:aws:anonymous-ip-list"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "HostingProviderIPList",
              "LabelNamespace",
              "awswaf:managed:aws:anonymous-ip-list"
            ]
          ]
          period = 300
          stat   = "Average"
          region = "${var.aws_region}"
          title  = "AWSManagedRulesAnonymousIpList"
        }
      },
      {
        type   = "metric"
        x      = 12
        y      = 24
        width  = 24
        height = 8

        properties = {
          view = "table"
          stacked = false
          metrics = [
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "AWSManagedIPReputationList",
              "LabelNamespace",
              "awswaf:managed:aws:amazon-ip-list"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "AWSManagedIPReputationList",
              "LabelNamespace",
              "awswaf:managed:aws:amazon-ip-list"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "AWSManagedIPDDoSList",
              "LabelNamespace",
              "awswaf:managed:aws:amazon-ip-list"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "AWSManagedIPDDoSList",
              "LabelNamespace",
              "awswaf:managed:aws:amazon-ip-list"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "AWSManagedReconnaissanceList",
              "LabelNamespace",
              "awswaf:managed:aws:amazon-ip-list"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "AWSManagedReconnaissanceList",
              "LabelNamespace",
              "awswaf:managed:aws:amazon-ip-list"
            ]
          ]
          period = 300
          stat   = "Average"
          region = "${var.aws_region}"
          title  = "AWSManagedRulesAmazonIpReputationList"
        }
      },
      {
        type   = "metric"
        x      = 12
        y      = 24
        width  = 24
        height = 6

        properties = {
          view = "table"
          stacked = false
          metrics = [
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "AdminProtection_URIPath",
              "LabelNamespace",
              "awswaf:managed:aws:admin-protection"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "AdminProtection_URIPath",
              "LabelNamespace",
              "awswaf:managed:aws:admin-protection"
            ]
          ]
          period = 300
          stat   = "Average"
          region = "${var.aws_region}"
          title  = "AWSManagedRulesAdminProtectionRuleSet"
        }
      },
      {
        type   = "metric"
        x      = 12
        y      = 24
        width  = 24
        height = 10

        properties = {
          view = "table"
          stacked = false
          metrics = [
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "SQLiExtendedPatterns_QUERYARGUMENTS",
              "LabelNamespace",
              "awswaf:managed:aws:sql-database"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "SQLiExtendedPatterns_QUERYARGUMENTS",
              "LabelNamespace",
              "awswaf:managed:aws:sql-database"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "SQLi_QUERYARGUMENTS",
              "LabelNamespace",
              "awswaf:managed:aws:sql-database"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "SQLi_QUERYARGUMENTS",
              "LabelNamespace",
              "awswaf:managed:aws:sql-database"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "SQLi_BODY",
              "LabelNamespace",
              "awswaf:managed:aws:sql-database"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "SQLi_BODY",
              "LabelNamespace",
              "awswaf:managed:aws:sql-database"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "SQLi_COOKIE",
              "LabelNamespace",
              "awswaf:managed:aws:sql-database"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "SQLi_COOKIE",
              "LabelNamespace",
              "awswaf:managed:aws:sql-database"
            ],
            [
              "AWS/WAFV2",
              "AllowedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "SQLi_URIPATH",
              "LabelNamespace",
              "awswaf:managed:aws:sql-database"
            ],
            [
              "AWS/WAFV2",
              "BlockedRequests",
              "WebACL",
              "${var.prefix}_WAF_ACL",
              "Region",
              "${var.aws_region}",
              "LabelName",
              "SQLi_URIPATH",
              "LabelNamespace",
              "awswaf:managed:aws:sql-database"
            ]
          ]
          period = 300
          stat   = "Average"
          region = "${var.aws_region}"
          title  = "AWSManagedRulesSQLiRuleSet"
        }
      }
      
    ]
  })
}